---
- name: creating namespace
  hosts: localhost
  tasks:
    - name: Create the 'linuxvm' namespace
      kubernetes.core.k8s:
        name: linuxvm
        kind: Namespace
        api_version: v1
        state: present
