---
- name: Start a Virtual Machine in OpenShift Virtualization via API
  hosts: localhost
  gather_facts: false
  vars:
    api_url: "{{ k8s_auth_host }}/apis/subresources.kubevirt.io/v1/namespaces/{{ mynamespace }}/virtualmachines/{{ myvm }}/start"
  tasks:
    - name: Start VM using OpenShift API
      uri:
        url: "{{ api_url }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ k8s_auth_api_key }}"
        validate_certs: no
      register: result

    - name: Show API response
      debug:
        var: result
