---
- name: List Virtual Machines in OpenShift
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Get Virtual Machines from my namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: VirtualMachine
        namespace: "{{ mynamespace }}"
      register: vms

    - name: Get a list of all pods from my namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ mynamespace }}"
      register: pod_list

    - name: Display Virtual Machines
      debug:
        msg: "{{ vms.resources | map(attribute='metadata.name') | list }}"

    - name: Display Pods
      debug:
        msg: "{{ pods_list.resources | map(attribute='metadata.name') | list }}"


