---
- name: rhc RHEL system role
  hosts: all
  vars:
    rhc_auth:
      activation_keys:
        keys:
          - "{{ activation_key }}"
        rhc_organization: "{{ organization_id }}"
  tasks:
    - name: register rhel with rhc role
      redhat.rhel_system_roles.rhc:
