---
- name: Start a Virtual Machine in OpenShift Virtualization via API
  hosts: localhost
  gather_facts: false
  vars:
    SANDBOX_HOST_VAR: "{{ lookup('env', 'SANDBOX_HOST') | default('SANDBOX_HOST_NOT_FOUND', true) }}"
    SANDBOX_BEARER_TOKEN_VAR: "{{ lookup('env', 'SANDBOX_BEARER_TOKEN') | default('SANDBOX_BEARER_NOT_FOUND', true) }}"
    api_url: "{{ SANDBOX_HOST_VAR }}/apis/subresources.kubevirt.io/v1/namespaces/{{ mynamespace }}/virtualmachines/{{ myvm }}/start"
  tasks:
        
    - name: Start VM using OpenShift API
      ansible.builtin.uri:
        url: "{{ api_url }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ SANDBOX_BEARER_TOKEN_VAR }}"
        validate_certs: no
      register: result

    - name: Show API response
      debug:
        var: result
