---
- name: Start an existing KubeVirt VirtualMachine
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Start the VM
      redhat.openshift_virtualization.kubevirt_vm:
        namespace: "{{ mynamespace }}"
        name: "{{ myvm }}"
        running: true
